name: Compatibility

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  compatibility-semistandard:
    uses: ./.github/workflows/compatibility.yml
    with:
      moduleSet: semistandard-filtered

  compatibility-standard:
    uses: ./.github/workflows/compatibility.yml
    with:
      moduleSet: standard-filtered

  compatibility-ts-standard:
    uses: ./.github/workflows/compatibility.yml
    with:
      moduleSet: ts-standard-filtered
