name: Compatibility standard

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  compatibility:
    strategy:
      fail-fast: false
      matrix:
        flags: ['', '--ts']
    uses: ./.github/workflows/compatibility.yml
    with:
      moduleSet: standard-filtered
      flags: ${{ matrix.flags }}
