name: Compatibility ts-standard

on:
  workflow_run:
    workflows: ["Tests"]
    branches: [main]
    types:
      - completed
  pull_request:
    branches:
      - main

jobs:
  compatibility:
    if: (github.event.workflow_run.conclusion || 'success') == 'success'
    uses: ./.github/workflows/compatibility.yml
    with:
      moduleSet: ts-standard-filtered
      flags: '--ts'
