name: Compatibility ts-standard

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  compatibility:
    uses: ./.github/workflows/compatibility.yml
    with:
      moduleSet: ts-standard-filtered
